improvement to verify script for macos users

diff --git a/bin/validate_one_exercise b/bin/validate_one_exercise
--- a/bin/validate_one_exercise
+++ b/bin/validate_one_exercise
@@ -31,10 +31,14 @@ readarray -t editor_files < <(jq -r '.files.editor[]?' "$config")
 # hello-world has no skips
 # neither do concept exercises
 if [[ ${exercise} != "hello-world" ]] && ! [[ $PWD =~ exercises/concept/ ]]; then
+    # check for GNU grep from homebrew
+    command -v ggrep >/dev/null && grep=ggrep || grep=grep
+    $grep -qP _ <<< _ 2>/dev/null || die "GNU grep is required for -P option: install it with homebrew"
+
     # a PCRE: the `\Q...\E` defines a literal segment
     # shellcheck disable=SC2016 # no expansion wanted inside ''
     skip_re='^\s*#+\s*\Q[[ $BATS_RUN_SKIPPED == "true" ]] || skip\E$'
-    num_skip_comments=$(grep -cP "${skip_re}" "${tests}") || :
+    num_skip_comments=$($grep -cP "${skip_re}" "${tests}") || :
     (( num_skip_comments == 1 )) || die "There should be exactly one commented skip directive in ${tests}"
 fi
 
